version: "3"

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - code-with-deposit

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  # airflow-init:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   entrypoint: /bin/bash
  #   command:
  #     - -c
  #     - |
  #       airflow db init &&
  #       airflow users create \
  #         --username admin \
  #         --firstname Admin \
  #         --lastname User \
  #         --role Admin \
  #         --email admin@example.com \
  #         --password admin &&
  #       airflow db check
  #   environment:
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=False
  #   healthcheck:
  #     test: ["CMD", "airflow", "db", "check"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    networks:
      - code-with-deposit

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    networks:
      - code-with-deposit

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/airflow/notebooks
    networks:
      - code-with-deposit

networks:
  code-with-deposit:
