version: "3"

x-spark-common: &spark-common
  image: bitnami/spark:3.4
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - code-with-deposit

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./dags:/opt/airflow/dags/
      - ./logs:/opt/airflow/logs/
      - ./notebooks:/opt/airflow/notebooks
    depends_on:
      - webserver
      - spark-master
    # environment:
    #   - SPARK_MASTER=spark://spark-master:7077
    #   - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-arm64
    networks:
      - code-with-deposit

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags/
      - ./logs:/opt/airflow/dags/
    networks:
      - code-with-deposit

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - webserver
  #   volumes:
  #     - ./dags:/opt/airflow/dags/
  #     - ./logs:/opt/airflow/dags/
  #   networks:
  #     - code-with-deposit

networks:
  code-with-deposit:
    driver: bridge
